-- ============================================================
-- HabitQuest Backend - Seed Data (v2)
-- Migration 004
-- ============================================================

insert into public.habits (
  internal_id, type, slug, title_tr, title_en, description_tr, description_en,
  icon, unit, base_daily_points, difficulty_weight, streak_multiplier_cap, effort_multiplier,
  health_impact, mental_discipline, financial_impact, time_impact, social_impact,
  target_direction, default_start_value, default_target_value,
  step_penalty_reward, adaptation_coefficient, activity_converters,
  category_tag, risk_level, calories_per_minute, calorie_to_point_rate
) values
('substance_quit_001', 'NEGATIVE_BYPASS', 'smoking_cessation',
 'Sigarayı Bırakma', 'Quit Smoking', 'Sigara içme alışkanlığını bırakma programı', 'Smoking cessation program',
 '🚭', 'adet', 10.0, 1.4, 2.5, 0.0, 10, 9, 9, 7, 6, 'DECREASE', 20, 0, -2.0, 1.2,
 '[{"trigger_slug":"physical_activity","input_unit":"minutes","point_conversion":0.15,"max_bonus_limit":5.0},
   {"trigger_slug":"water_intake","input_unit":"liters","point_conversion":1.0,"max_bonus_limit":3.0},
   {"trigger_slug":"deep_breathing","input_unit":"minutes","point_conversion":0.3,"max_bonus_limit":3.0}]'::jsonb,
 'ADDICTION', 'CRITICAL', 0, 0),
('substance_quit_002', 'NEGATIVE_BYPASS', 'alcohol_cessation',
 'Alkolü Bırakma', 'Quit Alcohol', 'Alkol tüketimini bırakma programı', 'Alcohol cessation program',
 '🍷', 'kadeh', 8.0, 1.3, 2.5, 0.0, 9, 9, 8, 6, 7, 'DECREASE', 4, 0, -2.5, 1.3,
 '[{"trigger_slug":"physical_activity","input_unit":"minutes","point_conversion":0.12,"max_bonus_limit":4.0},
   {"trigger_slug":"social_activity","input_unit":"events","point_conversion":2.0,"max_bonus_limit":4.0}]'::jsonb,
 'ADDICTION', 'HIGH', 0, 0),
('fitness_build_001', 'POSITIVE_BUILD', 'daily_walking',
 'Günlük Yürüyüş', 'Daily Walking', 'Her gün belirli süre yürüyüş yapma', 'Walk a set amount daily',
 '🚶', 'dakika', 6.0, 1.0, 2.0, 0.1, 7, 4, 2, 6, 3, 'INCREASE', 0, 30, 0.2, 1.0,
 '[{"trigger_slug":"water_intake","input_unit":"liters","point_conversion":0.5,"max_bonus_limit":2.0}]'::jsonb,
 'FITNESS', 'LOW', 4.0, 0.01),
('nutrition_quit_001', 'NEGATIVE_BYPASS', 'sugar_reduction',
 'Şeker Tüketimini Azaltma', 'Reduce Sugar Intake', 'Günlük şeker tüketimini azaltma', 'Reduce daily sugar consumption',
 '🍬', 'gram', 7.0, 1.1, 2.0, 0.0, 8, 7, 5, 3, 2, 'DECREASE', 80, 25, -0.1, 1.0,
 '[{"trigger_slug":"fruit_intake","input_unit":"porsiyon","point_conversion":1.5,"max_bonus_limit":3.0}]'::jsonb,
 'NUTRITION', 'MEDIUM', 0, 0),
('mental_build_001', 'POSITIVE_BUILD', 'daily_reading',
 'Günlük Kitap Okuma', 'Daily Reading', 'Her gün kitap okuma alışkanlığı', 'Build a daily reading habit',
 '📚', 'sayfa', 5.0, 0.9, 2.0, 0.0, 3, 6, 2, 8, 3, 'INCREASE', 0, 20, 0.15, 1.0,
 '[]'::jsonb, 'MENTAL', 'LOW', 0, 0),
('digital_quit_001', 'NEGATIVE_BYPASS', 'social_media_reduction',
 'Sosyal Medya Süresini Azaltma', 'Reduce Social Media Time', 'Günlük sosyal medya kullanımını azaltma', 'Cut down daily social media usage',
 '📱', 'dakika', 6.0, 1.0, 2.0, 0.0, 4, 7, 2, 9, 5, 'DECREASE', 180, 30, -0.05, 1.0,
 '[{"trigger_slug":"physical_activity","input_unit":"minutes","point_conversion":0.1,"max_bonus_limit":3.0},
   {"trigger_slug":"reading","input_unit":"pages","point_conversion":0.2,"max_bonus_limit":2.0}]'::jsonb,
 'DIGITAL_WELLNESS', 'MEDIUM', 0, 0),
('health_build_001', 'POSITIVE_BUILD', 'water_intake',
 'Günlük Su İçme', 'Daily Water Intake', 'Her gün yeterli su tüketme', 'Drink enough water daily',
 '💧', 'litre', 4.0, 0.8, 1.8, 0.0, 6, 3, 1, 2, 1, 'INCREASE', 0, 2.5, 0.5, 1.0,
 '[]'::jsonb, 'HEALTH', 'LOW', 0, 0),
('fitness_build_002', 'POSITIVE_BUILD', 'daily_exercise',
 'Günlük Egzersiz', 'Daily Exercise', 'Her gün egzersiz yapma alışkanlığı', 'Build a daily exercise routine',
 '💪', 'dakika', 8.0, 1.2, 2.0, 0.12, 9, 7, 3, 7, 4, 'INCREASE', 0, 45, 0.2, 1.0,
 '[{"trigger_slug":"water_intake","input_unit":"liters","point_conversion":0.5,"max_bonus_limit":2.0}]'::jsonb,
 'FITNESS', 'LOW', 7.5, 0.012),
('nutrition_quit_002', 'NEGATIVE_BYPASS', 'fast_food_cessation',
 'Fast Food''u Bırakma', 'Quit Fast Food', 'Fast food tüketimini bırakma', 'Stop eating fast food',
 '🍔', 'öğün', 7.0, 1.1, 2.0, 0.0, 7, 6, 7, 4, 3, 'DECREASE', 2, 0, -3.0, 1.1,
 '[{"trigger_slug":"home_cooking","input_unit":"meals","point_conversion":2.0,"max_bonus_limit":4.0},
   {"trigger_slug":"physical_activity","input_unit":"minutes","point_conversion":0.1,"max_bonus_limit":3.0}]'::jsonb,
 'NUTRITION', 'MEDIUM', 0, 0)
on conflict (slug) do nothing;
